version: '3'
services:

  spam_detection_backend:
    build:
      context: ./Docker
      dockerfile: Dockerfile
    env_file:
      - env/.env_prod
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
      - ./data:/data
      - ./models:/models
    command: bash -c "uvicorn app.run:app"