# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  
  job_1:
    name: Setup envrionments & app deployment
    runs-on: ubuntu-latest  
  
    steps:
  
      - uses: actions/checkout@v2
    
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Application deployment
        run: bash -c "source start.sh & sleep 5"

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: List docker containers
        run: bash -c "docker ps -a"
    
  job_2:
    runs-on: ubuntu-latest

    steps:
      - name: Set up test envrionments
        run: bash -c "pip3 install -r Docker/Requirements.txt"

      - name: Test basic functionality
        run: bash -c "pytest -v --exitfirst tests/test_basic_functionality.py"

      - name: Test stability
        run: bash -c "pytest -v --exitfirst tests/test_stability.py"
